# Generated by Django 6.1.1 on 2026-09-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('compatible_bikes', models.ManyToManyField(blank=True, related_name='compatible_parts', to='compatibility.bikemodel')),
            ],
        ),
    ]
